name: "Venafi Vault Wizard Helm Example"
on:
  push:
  pull_request:
jobs:
  example:
    name: "Build and Run Example"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/helm
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v3
      - name: "Set up Go 1.18"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: install k8s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      - name: "Build"
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build

      - name: "Helm Dependency Update"
        run: helm dependency update
      - name: "Helm Install Cluster"
        run: helm install vvwtestcluster .
      - name: "Kubectl Exec Cluster"
        uses: actions-hub/kubectl@master
        with:
          args: exec -i vvwtestcluster-vault-0 -- vault operator init -key-shares=1 -key-threshold=1 -format=json > init-keys.json
