name: "Venafi Vault Wizard Helm Example"
on:
  push:
  pull_request:
jobs:
  example:
    name: "Build and Run Example"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/helm
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v3
      - name: "Set up Go 1.18"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: "install k8s"
        uses: helm/kind-action@v1.2.0
        with: 
          cluster_name: kind
      - name: "setup helm"
        uses: azure/setup-helm@v1
        with: 
          version: v3.8.2 
      - run: helm version
      - name: "Build"
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build
      - name: "Helm Dependency Update"
        run: helm dependency update
      - name: "Check cluster info"
        run: kubectl cluster-info
      - run: kind load docker-image vault-with-venafi-plugins
      - name: "Helm Install Cluster"
        run: helm install vvwtestcluster .
      - name: "Get pods"
        run: kubectl get pods
      - run: sleep 30
      - name: "Get pods"
        run: kubectl get pods
      - run: kubectl describe pod vvwtestcluster-vault-0
      - name: "Run pod"
        run: kubectl exec vvwtestcluster-vault-0 -- vault operator init -key-shares=1 -key-threshold=1 -format=json > init-keys.json
      - run: kubectl exec vvwtestcluster-vault-0 -- vault operator unseal $(jq -r '.unseal_keys_b64 | first' init-keys.json)
      - run: |
          echo "Root token: $(jq -r '.root_token' init-keys.json)"
          export VAULT_TOKEN=$(jq -r '.root_token' init-keys.json)
          kubectl exec vvwtestcluster-vault-0 -- vault status
          ../../bin/vvw apply -f tpp-vvw.hcl
          ../../bin/vvw apply -f vaas-vvw.hcl